initial_positions:
  joint_a1: 0.4124
  joint_a2: 1.2447
  joint_a3: 1.4574
  joint_a4: 1.0436
  joint_a5: 2.7578
  joint_a6: 1.7968
  joint_a7: -1.8123


#initial_positions:
#  joint_a1: 1.0
#  joint_a2: -0.2
#  joint_a3: -0.7
#  joint_a4: 1.5
#  joint_a5: 1.5
#  joint_a6: -0.5
#  joint_a7: -0.8
